export const IPC = {
  clickerStart: 'clicker:start',
  clickerStop: 'clicker:stop',
  clickerTick: 'clicker:tick',
  permCheck: 'perm:check',
  hotkeySet: 'hotkey:set',
  hotkeyStatus: 'hotkey:status',
  hotkeyFire: 'hotkey:fire',
  appShowMain: 'app:show-main',
  appHideMain: 'app:hide-main',
  appHidePopover: 'app:hide-popover',
  appMode: 'app:mode',
  mainResizeByDelta: 'main:resize-by-delta',
  pickerStart: 'picker:start',
  pickerPick: 'picker:pick',
  pickerCancel: 'picker:cancel',
  regionPickerStart: 'region-picker:start',
  regionPickerPick: 'region-picker:pick',
  regionPickerCancel: 'region-picker:cancel',
  autonomyStart: 'autonomy:start',
  autonomyStop: 'autonomy:stop',
  autonomyTick: 'autonomy:tick',
  autonomyCapture: 'autonomy:capture',
  autonomyMatch: 'autonomy:match',
  autonomySample: 'autonomy:sample',
  // OCR, app focus, idle detection (helper-backed).
  ocrRecognize: 'vision:ocr',
  focusApp: 'system:focus-app',
  listApps: 'system:list-apps',
  idleSeconds: 'system:idle-seconds',
  // Path recorder — polls the cursor from the main process at ~60Hz.
  pathRecordStart: 'path:record:start',
  pathRecordStop: 'path:record:stop',
  pathRecordTick: 'path:record:tick',
  // Scheduling triggers — time / event based autonomy launches.
  triggersList: 'triggers:list',
  triggersSet: 'triggers:set',
  triggersRemove: 'triggers:remove',
  triggersFire: 'triggers:fire',
  triggersStatus: 'triggers:status',
  settingsLaunchAtLoginGet: 'settings:launch-at-login:get',
  settingsLaunchAtLoginSet: 'settings:launch-at-login:set',
  settingsAlwaysOnTopSet: 'settings:always-on-top:set',
  settingsDockVisibleSet: 'settings:dock-visible:set',
  settingsCloseToTraySet: 'settings:close-to-tray:set',
  settingsPopoverAutoHideSet: 'settings:popover-auto-hide:set',
  settingsPreventSleepSet: 'settings:prevent-sleep:set',
  settingsOpenAccessibility: 'settings:open-accessibility',
  settingsOpenScreenRecording: 'settings:open-screen-recording',
  // Cross-window renderer-state sync. Each renderer publishes the persisted
  // slice of its zustand store here whenever it changes; the main process
  // rebroadcasts it to every OTHER window so every open renderer (full app,
  // popover, etc.) stays in lockstep on theme / config / modules / hotkeys.
  stateBroadcast: 'state:broadcast',
} as const;
